In [2]:
import numpy as np

In [5]:
a = np.array([ 5, 6, 7, 8]) #buat array secara manual

In [7]:
print(a[-1])

8


In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
print(np.arange(0,10,5))

[0 5]


In [4]:
print(np.arange(1,9,3)) #buat array dengan range tertentu

[1 4 7]


In [8]:
arr = np.array([1, 2, 3])

In [12]:
a = arr

In [15]:
np.append(a, [4,5]) #menambahkan nilai ke dalam array 

array([1, 2, 3, 4, 5])

In [16]:
print(np.append(a, [4,5]))

[1 2 3 4 5]


In [17]:
np.delete(a, -2) #menghapus nilai di dalam array

array([1, 3])

In [42]:
a_array = np.array([[[3,7,4,2],
                     [2,3,4,1]],
                
                    [[2,3,6,4],
                     [5,1,3,7]]])

In [19]:
np.sort(a) #mengurutkan angka di dalam array 

array([0, 2, 3, 4, 7])

In [30]:
a_array.ndim

3

In [31]:
a_array.size

20

In [32]:
a_array.shape #(a,b,c) a for row, b for colomn, c for how many inside

(2, 2, 5)

In [43]:
a_array.reshape(2,4,2) 

array([[[3, 7],
        [4, 2],
        [2, 3],
        [4, 1]],

       [[2, 3],
        [6, 4],
        [5, 1],
        [3, 7]]])

In [49]:
print(a_array)

[[[3 7 4 2]
  [2 3 4 1]]

 [[2 3 6 4]
  [5 1 3 7]]]


In [44]:
a2_array = a_array[np.newaxis]

In [116]:
a3_array = np.array([[[3,4,5,6,7], [2,3,4,5,5]], 
                     [[1,2,3,4,5], [1,2,5,6,7]],
                     [[1,2,3,4,5], [7,8,4,0,2]]])


In [118]:
col_vector = a3_array[:, np.newaxis]
print(col_vector)

[[[[3 4 5 6 7]
   [2 3 4 5 5]]]


 [[[1 2 3 4 5]
   [1 2 5 6 7]]]


 [[[1 2 3 4 5]
   [7 8 4 0 2]]]]


In [113]:
row_vector = a3_array[np.newaxis, :]
print(row_vector)

[[[3 4 5 6 7]
  [2 3 4 5 5]
  [1 2 3 4 5]
  [1 2 5 6 7]
  [1 2 3 4 5]
  [7 8 4 0 2]]]


In [117]:
print(a3_array.shape)

(3, 2, 5)


In [126]:
b = np.expand_dims(a3_array, axis=1) #Add new dimension

In [127]:
print(b.shape)

(3, 1, 2, 5)


In [128]:
print(a3_array)

[[[3 4 5 6 7]
  [2 3 4 5 5]]

 [[1 2 3 4 5]
  [1 2 5 6 7]]

 [[1 2 3 4 5]
  [7 8 4 0 2]]]


In [199]:
data1 = np.array([[2,3,4], [2,5,6], [7,8,9]])
data2 = np.array([[11,23,44], [22,31,45], [21,67,89]])
DataMoreThanTwo = data1[data1>2]
print(DataMoreThanTwo)

[3 4 5 6 7 8 9]


In [206]:
data3 = np.hstack((data1, data2))
print(data3)

[[ 2  3  4 11 23 44]
 [ 2  5  6 22 31 45]
 [ 7  8  9 21 67 89]]


In [207]:
data3 = np.vstack((data1, data2))
print(data3)

[[ 2  3  4]
 [ 2  5  6]
 [ 7  8  9]
 [11 23 44]
 [22 31 45]
 [21 67 89]]


In [211]:
data4 = np.array([1,2,3,4,5,6,7,8])
#np.hsplit(data4, 4)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [219]:
data5 = data4.view()
data5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [223]:
data5 = data4[0:1].copy()
data5

array([1])

In [241]:
a3_array.shape

(3, 2, 5)

In [248]:
print(a3_array.sum(axis = 0).shape) #sum the rows
print(a3_array.sum(axis = 1).shape) #sum the column

(2, 5)
(3, 5)


In [270]:
b1 = np.array([20,10,5])
b2 = np.array([30,5,6])

In [259]:
b1 + b2.sum() * 2

array([52, 42, 37])

In [272]:
b3 = np.vstack((b1, b2))
b3.max(axis=0)

array([30, 10,  6])